#pragma once
#include <map>
#include <string>

enum class KeywordsType {
	MoreEqual,
	LessEqual,
	More,
	Less,
	Equal,
	NotEqual,
	Define,
	DoubleDot,
	Plus,
	Minus,
	Multiply,
	OpenComment,
	CloseComment,
	Division,
	OpenBracket,
	CloseBracket,
	OpenFigure,
	CloseFigure,
	OpenSquare,
	CloseSquare,
	Quote,
	Dot,
	TwoDots,
	Comma,
	Pow,
	Semicolon,
	If,
	Do,
	Of,
	Or,
	In,
	To,
	End,
	Var,
	Div,
	And,
	Not,
	For,
	Mod,
	Nil,
	Set,
	Then,
	Else,
	Case,
	File,
	Goto,
	Type,
	With,
	Begin,
	While,
	Array,
	Const,
	Label,
	Until,
	DownTo,
	Packed,
	Record,
	Repeat,
	Program,
	Function,
	Procedure,
	WriteLn,
	ReadLn
};

const std::map<std::string, KeywordsType> keywordsDict = {{
	{">=", KeywordsType::MoreEqual},
	{"<=", KeywordsType::LessEqual},
	{">", KeywordsType::More},
	{"<", KeywordsType::Less},
	{"=", KeywordsType::Equal},
	{"<>", KeywordsType::NotEqual},
	{":=", KeywordsType::Define},
	{":", KeywordsType::DoubleDot},
	{"+", KeywordsType::Plus},
	{"-", KeywordsType::Minus},
	{"(*", KeywordsType::OpenComment},
	{"*)", KeywordsType::CloseComment},
	{"/", KeywordsType::Division},
	{"(", KeywordsType::OpenBracket},
	{")", KeywordsType::CloseBracket},
	{"{", KeywordsType::OpenFigure},
	{"}", KeywordsType::CloseFigure},
	{"[", KeywordsType::OpenSquare},
	{"]", KeywordsType::CloseSquare},
	{"'", KeywordsType::Quote},
	{".", KeywordsType::Dot},
	{"..", KeywordsType::TwoDots},
	{",", KeywordsType::Comma},
	{"^", KeywordsType::Pow},
	{";", KeywordsType::Semicolon},
	{"if", KeywordsType::If},
	{"do", KeywordsType::Do},
	{"of", KeywordsType::Of},
	{"or", KeywordsType::Or},
	{"in", KeywordsType::In},
	{"to", KeywordsType::To},
	{"end", KeywordsType::End},
	{"var", KeywordsType::Var},
	{"div", KeywordsType::Div},
	{"and", KeywordsType::And},
	{"not", KeywordsType::Not},
	{"for", KeywordsType::For},
	{"mod", KeywordsType::Mod},
	{"nil", KeywordsType::Nil},
	{"set", KeywordsType::Set},
	{"then", KeywordsType::Then},
	{"else", KeywordsType::Else},
	{"case", KeywordsType::Case},
	{"file", KeywordsType::File},
	{"goto", KeywordsType::Goto},
	{"type", KeywordsType::Type},
	{"with", KeywordsType::With},
	{"begin", KeywordsType::Begin},
	{"while", KeywordsType::While},
	{"array", KeywordsType::Array},
	{"const", KeywordsType::Const},
	{"label", KeywordsType::Label},
	{"until", KeywordsType::Until},
	{"downto", KeywordsType::DownTo},
	{"packed", KeywordsType::Packed},
	{"record", KeywordsType::Record},
	{"repeat", KeywordsType::Repeat},
	{"program", KeywordsType::Program},
	{"function", KeywordsType::Function},
	{"procedure", KeywordsType::Procedure},
	{"readln", KeywordsType::ReadLn},
	{"writeln", KeywordsType::WriteLn}
}};

const std::map<KeywordsType, std::string> enumToKeywords = { {
	{KeywordsType::MoreEqual, ">="},
	{KeywordsType::LessEqual, "<="},
	{KeywordsType::More, ">"},
	{KeywordsType::Less, "<"},
	{KeywordsType::Equal, "="},
	{KeywordsType::NotEqual, "<>"},
	{KeywordsType::Define, ":="},
	{KeywordsType::DoubleDot, ":"},
	{KeywordsType::Plus, "+"},
	{KeywordsType::Minus, "-"},
	{KeywordsType::OpenComment, "(*"},
	{KeywordsType::CloseComment, "*)"},
	{KeywordsType::Division, "/"},
	{KeywordsType::OpenBracket, "("},
	{KeywordsType::CloseBracket, ")"},
	{KeywordsType::OpenFigure, "{"},
	{KeywordsType::CloseFigure, "}"},
	{KeywordsType::OpenSquare, "["},
	{KeywordsType::CloseSquare, "]"},
	{KeywordsType::Quote, "'"},
	{KeywordsType::Dot, "."},
	{KeywordsType::TwoDots, ".."},
	{KeywordsType::Comma, ","},
	{KeywordsType::Pow, "^"},
	{KeywordsType::Semicolon, ";"},
	{KeywordsType::If, "if"},
	{KeywordsType::Do, "do"},
	{KeywordsType::Of, "of"},
	{KeywordsType::Or, "or"},
	{KeywordsType::In, "in"},
	{KeywordsType::To, "to"},
	{KeywordsType::End, "end"},
	{KeywordsType::Var, "var"},
	{KeywordsType::Div, "div"},
	{KeywordsType::And, "and"},
	{KeywordsType::Not, "not"},
	{KeywordsType::For, "for"},
	{KeywordsType::Mod, "mod"},
	{KeywordsType::Nil, "nil"},
	{KeywordsType::Set, "set"},
	{KeywordsType::Then, "then"},
	{KeywordsType::Else, "else"},
	{KeywordsType::Case, "case"},
	{KeywordsType::File, "file"},
	{KeywordsType::Goto, "goto"},
	{KeywordsType::Type, "type"},
	{KeywordsType::With, "with"},
	{KeywordsType::Begin, "begin"},
	{KeywordsType::While, "while"},
	{KeywordsType::Array, "array"},
	{KeywordsType::Const, "const"},
	{KeywordsType::Label, "label"},
	{KeywordsType::Until, "until"},
	{KeywordsType::DownTo, "downto"},
	{KeywordsType::Packed, "packed"},
	{KeywordsType::Record, "record"},
	{KeywordsType::Repeat, "repeat"},
	{KeywordsType::Program, "program"},
	{KeywordsType::Function, "function"},
	{KeywordsType::Procedure, "procedure"},
	{KeywordsType::ReadLn, "readln"},
	{KeywordsType::WriteLn, "writeln"}
}};